// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LemonadeProviderw.Runtime")>]
[<assembly: AssemblyProductAttribute("LemonadeProviderw")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing LemonadeProviderw.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LemonadeProviderw.Runtime"
    let [<Literal>] AssemblyProduct = "LemonadeProviderw"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing LemonadeProviderw."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
